version: '3'

services: 
    db:
        build: 
            context: ./mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true        
        networks: 
            - mynetwork
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysqldata:/var/lib/mysql

    app:
        build: 
            context: ./node
            dockerfile: Dockerfile.prod
        container_name: app
        ports:  
            - "3000:3000"
        networks: 
            - mynetwork
        volumes: 
            - ./node:/usr/src/app
        tty: true
    nginx:
        build:             
            context: ./nginx
        container_name: nginx
        ports:  
            - "8085:80"
        networks: 
            - mynetwork    
networks: 
    mynetwork:
        driver: bridge

volumes:
    mysqldata:
